# Generated by Django 4.2.13 on 2026-05-29 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "job_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("responsibilities", models.TextField(blank=True)),
                ("min_experience", models.PositiveIntegerField(default=0)),
                ("max_experience", models.PositiveIntegerField(default=20)),
                (
                    "min_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("vacancies", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("on_hold", "On Hold"),
                            ("closed", "Closed"),
                            ("filled", "Filled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "ai_score_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=70.0,
                        help_text="Minimum AI match score (%) for auto-shortlist",
                        max_digits=5,
                    ),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "ai_optimized_jd",
                    models.TextField(
                        blank=True, help_text="AI-optimized job description"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitions",
                        to="master.department",
                    ),
                ),
                (
                    "employment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitions",
                        to="master.employmenttype",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitions",
                        to="master.joblevel",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitions",
                        to="master.location",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisitions_posted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "required_skills",
                    models.ManyToManyField(
                        blank=True, related_name="requisitions", to="master.techskill"
                    ),
                ),
            ],
            options={
                "db_table": "main_job_requisition",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "candidate_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("N", "Prefer not to say"),
                        ],
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("current_location", models.CharField(blank=True, max_length=200)),
                ("current_company", models.CharField(blank=True, max_length=200)),
                ("current_title", models.CharField(blank=True, max_length=200)),
                (
                    "total_experience",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "resume_text",
                    models.TextField(
                        blank=True, help_text="Extracted resume text for AI processing"
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("portal", "Job Portal"),
                            ("linkedin", "LinkedIn"),
                            ("referral", "Referral"),
                            ("campus", "Campus Recruitment"),
                            ("agency", "Agency"),
                            ("direct", "Direct Application"),
                            ("ai_sourced", "AI Sourced"),
                        ],
                        default="portal",
                        max_length=20,
                    ),
                ),
                (
                    "ai_profile_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overall AI-assessed profile strength",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, related_name="candidates", to="master.techskill"
                    ),
                ),
            ],
            options={
                "db_table": "main_candidate",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "application_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("ai_screening", "AI Screening"),
                            ("shortlisted", "Shortlisted"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interviewed", "Interviewed"),
                            ("offer_extended", "Offer Extended"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="applied",
                        max_length=30,
                    ),
                ),
                ("applied_date", models.DateField(auto_now_add=True)),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "ai_match_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="AI computed match score (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("ai_screening_notes", models.TextField(blank=True)),
                ("ai_screened_at", models.DateTimeField(blank=True, null=True)),
                ("is_auto_shortlisted", models.BooleanField(default=False)),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="main.candidate",
                    ),
                ),
                (
                    "rejection_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="master.rejectionreason",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="main.jobrequisition",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "main_application",
                "ordering": ["-created_at"],
                "unique_together": {("candidate", "requisition")},
            },
        ),
    ]
