# Generated by Django 4.2.13 on 2026-05-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AITool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("ats", "Applicant Tracking System"),
                            ("screening", "Resume Screening"),
                            ("chatbot", "Chatbot / Virtual Assistant"),
                            ("video_ai", "Video Interview AI"),
                            ("predictive", "Predictive Analytics"),
                            ("jd_optimizer", "JD Optimizer"),
                            ("sourcing", "Candidate Sourcing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "accuracy_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_integrated", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "master_ai_tool",
                "ordering": ["tool_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "master_department",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmploymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "db_table": "master_employment_type",
            },
        ),
        migrations.CreateModel(
            name="JobLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("min_exp_years", models.PositiveIntegerField(default=0)),
                ("max_exp_years", models.PositiveIntegerField(default=50)),
            ],
            options={
                "db_table": "master_job_level",
                "ordering": ["min_exp_years"],
            },
        ),
        migrations.CreateModel(
            name="RejectionReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("reason", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "master_rejection_reason",
            },
        ),
        migrations.CreateModel(
            name="TechSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("language", "Programming Language"),
                            ("framework", "Framework/Library"),
                            ("database", "Database"),
                            ("cloud", "Cloud/DevOps"),
                            ("ai_ml", "AI/ML"),
                            ("soft_skill", "Soft Skill"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "master_tech_skill",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("is_remote", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "master_location",
                "unique_together": {("city", "state", "country")},
            },
        ),
    ]
