# Generated by Django 4.2.13 on 2026-05-29 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("offer_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "offered_salary",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("extended", "Extended"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "offer_letter",
                    models.FileField(blank=True, null=True, upload_to="offers/"),
                ),
                ("decline_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer",
                        to="main.application",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transactions_offer",
                "ordering": ["-offer_date"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("screening", "Screening Round"),
                            ("technical", "Technical Round"),
                            ("hr", "HR Round"),
                            ("managerial", "Managerial Round"),
                            ("panel", "Panel Interview"),
                            ("ai_video", "AI Video Interview"),
                        ],
                        max_length=20,
                    ),
                ),
                ("round_number", models.PositiveIntegerField(default=1)),
                ("scheduled_at", models.DateTimeField()),
                ("duration_mins", models.PositiveIntegerField(default=60)),
                (
                    "location_or_link",
                    models.CharField(
                        blank=True, help_text="Room or video link", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("on_hold", "On Hold"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True, help_text="Interviewer rating 1-5", null=True
                    ),
                ),
                (
                    "ai_assessment",
                    models.TextField(blank=True, help_text="AI video analysis notes"),
                ),
                (
                    "ai_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="main.application",
                    ),
                ),
                (
                    "interviewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="interviews_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interviews_scheduled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transactions_interview",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="AIToolUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("tool_name", models.CharField(max_length=100)),
                (
                    "score_generated",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("output_notes", models.TextField(blank=True)),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ai_tool",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usages",
                        to="master.aitool",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tool_usages",
                        to="main.application",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transactions_ai_tool_usage",
                "ordering": ["-created_at"],
            },
        ),
    ]
